I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/clearing.rpy", line 15, in script
    "Talonclaw does not have the strength to patrol more than once per day, so use it wisely."
  File "renpy/common/00action_other.rpy", line 582, in __call__
    rv = self.callable(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game_content/clearing.rpy", line 15, in script
    "Talonclaw does not have the strength to patrol more than once per day, so use it wisely."
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1455, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1106, in do_display
    display_say(who,
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 803, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 3286, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 791, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\behavior.py", line 1182, in event
    return handle_click(self.clicked)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\behavior.py", line 1103, in handle_click
    rv = run(action)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\behavior.py", line 394, in run
    new_rv = run(i, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 582, in __call__
    rv = self.callable(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Wed Feb 26 19:21:51 2025
