I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "game/screens/quest_screen.rpy", line 1, in execute
    screen quests_ui:
  File "game/screens/quest_screen.rpy", line 1, in execute
    screen quests_ui:
  File "game/screens/quest_screen.rpy", line 16, in execute
    frame:
  File "game/screens/quest_screen.rpy", line 20, in execute
    vbox:
  File "game/screens/quest_screen.rpy", line 37, in execute
    vbox:
  File "game/screens/quest_screen.rpy", line 39, in execute
    for quest in my_quests:
  File "game/screens/quest_screen.rpy", line 40, in execute
    if quest.failed:
  File "game/screens/quest_screen.rpy", line 40, in <module>
    if quest.failed:
AttributeError: 'Quest' object has no attribute 'failed'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/screens/quest_screen.rpy", line 1, in execute
    screen quests_ui:
  File "game/screens/quest_screen.rpy", line 1, in execute
    screen quests_ui:
  File "game/screens/quest_screen.rpy", line 16, in execute
    frame:
  File "game/screens/quest_screen.rpy", line 20, in execute
    vbox:
  File "game/screens/quest_screen.rpy", line 37, in execute
    vbox:
  File "game/screens/quest_screen.rpy", line 39, in execute
    for quest in my_quests:
  File "game/screens/quest_screen.rpy", line 40, in execute
    if quest.failed:
  File "game/screens/quest_screen.rpy", line 40, in <module>
    if quest.failed:
AttributeError: 'Quest' object has no attribute 'failed'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Sun Mar 30 18:33:35 2025
