I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/start.rpy", line 50, in script
    l "I should probably check out what's happening around camp."
Exception: Sayer 'l' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game_content/start.rpy", line 50, in script
    l "I should probably check out what's happening around camp."
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'l' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Thu Feb 13 15:35:41 2025
