I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/herb_gathering.rpy", line 90, in script
    call screen herb_gathering_screen
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: DynamicImage 'images/bg/herbbg_[i].png': could not find image. ('images/bg/herbbg_2.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game_content/herb_gathering.rpy", line 90, in script
    call screen herb_gathering_screen
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1980, in execute
    self.call("execute")
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1959, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\exports\statementexports.py", line 345, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 2 more times]
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 436, in visit_all
    callback(self)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\image.py", line 793, in per_interact
    self.find_target()
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\display\image.py", line 683, in find_target
    raise Exception(error)
Exception: DynamicImage 'images/bg/herbbg_[i].png': could not find image. ('images/bg/herbbg_2.png')

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Mon Mar 31 16:18:40 2025
